### ISSUE TITLE
EOS position in bot training

### ISSUE THREAD

**Issue by jld23** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#5]
@oswaldoludwig I've been adapting your code for my conversation file and I can't figure out the meaning of this [line](https://github.com/oswaldoludwig/Seq2seq-Chatbot-for-Keras/blob/master/train_bot.py#L157)
I got a variety of errors but if I set `l = np.where(sent==0)` the code runs. I don't know if that works or not. The same code is also at line 171.

Can explain what the EOS is doing?

Thanks!

**Comment by oswaldoludwig** [comment]
This is because you generated a new vocabulary. BOS and EOS mean begin and end of sentence. You have to check in your new dictionary the indices of these tokens and replace them in the code (they can change according to the frequency in your dataset, the current indices are 2 and 3, respectively). Should be nice to have a function to check automatically these indices, for users that want a new vocabulary. If you do it, please create a pull request.

**Comment by jld23** [comment]
Thank you. I only see a reference to EOS. Does the BOS play a role here?

**Comment by oswaldoludwig** [comment]
Yes, please see line 49 of train_bot.py, for instance. The index 2 is BOS.

**Comment by jld23** [comment]
Thank you for your help. I'll do a PR once I get things cleaned up.

**Comment by iuria21** [comment]
Hi, is there any other restriction? The padding is being done with the value 0, but the 0 value of the vocabulary may change also, doesn't it?
